// This Source Form is subject to the terms of the AQUA Software License, v. 1.0.
// Copyright (c) 2025 Aymeric Wibo

#include <aqua/kos.h>

static kos_fn_t const FNS[] = {
	{
		.name = "surface_from_win",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "instance"},
			{KOS_TYPE_OPAQUE_PTR, "win"},
		},
	},
	{
		.name = "device_from_wm",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "instance"},
			{KOS_TYPE_OPAQUE_PTR, "wm"},
		},
	},

	// This file is automatically generated by 'vdev/wgpu/gen.py'.
	// If you need to update this, read the 'vdev/wgpu/README.md' document.

	// clang-format off
// FNS:BEGIN
	{
		.name = "wgpuCreateInstance",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_BUF, "descriptor"},
		},
	},
	{
		.name = "wgpuGetInstanceCapabilities",
		.ret_type = KOS_TYPE_U32,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_BUF, "capabilities"},
		},
	},
	{
		.name = "wgpuGetProcAddress",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "procName"},
		},
	},
	{
		.name = "wgpuAdapterGetFeatures",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "adapter"},
			{KOS_TYPE_BUF, "features"},
		},
	},
	{
		.name = "wgpuAdapterGetInfo",
		.ret_type = KOS_TYPE_U32,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "adapter"},
			{KOS_TYPE_BUF, "info"},
		},
	},
	{
		.name = "wgpuAdapterGetLimits",
		.ret_type = KOS_TYPE_U32,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "adapter"},
			{KOS_TYPE_BUF, "limits"},
		},
	},
	{
		.name = "wgpuAdapterHasFeature",
		.ret_type = KOS_TYPE_BOOL,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "adapter"},
			{KOS_TYPE_U32, "feature"},
		},
	},
	{
		.name = "wgpuAdapterRequestDevice",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 3,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "adapter"},
			{KOS_TYPE_BUF, "descriptor"},
			{KOS_TYPE_BUF, "callbackInfo"},
		},
	},
	{
		.name = "wgpuAdapterAddRef",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "adapter"},
		},
	},
	{
		.name = "wgpuAdapterRelease",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "adapter"},
		},
	},
	{
		.name = "wgpuAdapterInfoFreeMembers",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_BUF, "adapterInfo"},
		},
	},
	{
		.name = "wgpuBindGroupSetLabel",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "bindGroup"},
			{KOS_TYPE_OPAQUE_PTR, "label"},
		},
	},
	{
		.name = "wgpuBindGroupAddRef",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "bindGroup"},
		},
	},
	{
		.name = "wgpuBindGroupRelease",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "bindGroup"},
		},
	},
	{
		.name = "wgpuBindGroupLayoutSetLabel",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "bindGroupLayout"},
			{KOS_TYPE_OPAQUE_PTR, "label"},
		},
	},
	{
		.name = "wgpuBindGroupLayoutAddRef",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "bindGroupLayout"},
		},
	},
	{
		.name = "wgpuBindGroupLayoutRelease",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "bindGroupLayout"},
		},
	},
	{
		.name = "wgpuBufferDestroy",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "buffer"},
		},
	},
	{
		.name = "wgpuBufferGetConstMappedRange",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 3,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "buffer"},
			{KOS_TYPE_U32, "offset"},
			{KOS_TYPE_U32, "size"},
		},
	},
	{
		.name = "wgpuBufferGetMapState",
		.ret_type = KOS_TYPE_U32,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "buffer"},
		},
	},
	{
		.name = "wgpuBufferGetMappedRange",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 3,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "buffer"},
			{KOS_TYPE_U32, "offset"},
			{KOS_TYPE_U32, "size"},
		},
	},
	{
		.name = "wgpuBufferGetSize",
		.ret_type = KOS_TYPE_U64,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "buffer"},
		},
	},
	{
		.name = "wgpuBufferGetUsage",
		.ret_type = KOS_TYPE_U64,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "buffer"},
		},
	},
	{
		.name = "wgpuBufferMapAsync",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 5,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "buffer"},
			{KOS_TYPE_U64, "mode"},
			{KOS_TYPE_U32, "offset"},
			{KOS_TYPE_U32, "size"},
			{KOS_TYPE_BUF, "callbackInfo"},
		},
	},
	{
		.name = "wgpuBufferSetLabel",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "buffer"},
			{KOS_TYPE_OPAQUE_PTR, "label"},
		},
	},
	{
		.name = "wgpuBufferUnmap",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "buffer"},
		},
	},
	{
		.name = "wgpuBufferAddRef",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "buffer"},
		},
	},
	{
		.name = "wgpuBufferRelease",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "buffer"},
		},
	},
	{
		.name = "wgpuCommandBufferSetLabel",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "commandBuffer"},
			{KOS_TYPE_OPAQUE_PTR, "label"},
		},
	},
	{
		.name = "wgpuCommandBufferAddRef",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "commandBuffer"},
		},
	},
	{
		.name = "wgpuCommandBufferRelease",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "commandBuffer"},
		},
	},
	{
		.name = "wgpuCommandEncoderBeginComputePass",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "commandEncoder"},
			{KOS_TYPE_BUF, "descriptor"},
		},
	},
	{
		.name = "wgpuCommandEncoderBeginRenderPass",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "commandEncoder"},
			{KOS_TYPE_BUF, "descriptor"},
		},
	},
	{
		.name = "wgpuCommandEncoderClearBuffer",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 4,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "commandEncoder"},
			{KOS_TYPE_OPAQUE_PTR, "buffer"},
			{KOS_TYPE_U64, "offset"},
			{KOS_TYPE_U64, "size"},
		},
	},
	{
		.name = "wgpuCommandEncoderCopyBufferToBuffer",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 6,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "commandEncoder"},
			{KOS_TYPE_OPAQUE_PTR, "source"},
			{KOS_TYPE_U64, "sourceOffset"},
			{KOS_TYPE_OPAQUE_PTR, "destination"},
			{KOS_TYPE_U64, "destinationOffset"},
			{KOS_TYPE_U64, "size"},
		},
	},
	{
		.name = "wgpuCommandEncoderCopyBufferToTexture",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 4,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "commandEncoder"},
			{KOS_TYPE_BUF, "source"},
			{KOS_TYPE_BUF, "destination"},
			{KOS_TYPE_BUF, "copySize"},
		},
	},
	{
		.name = "wgpuCommandEncoderCopyTextureToBuffer",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 4,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "commandEncoder"},
			{KOS_TYPE_BUF, "source"},
			{KOS_TYPE_BUF, "destination"},
			{KOS_TYPE_BUF, "copySize"},
		},
	},
	{
		.name = "wgpuCommandEncoderCopyTextureToTexture",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 4,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "commandEncoder"},
			{KOS_TYPE_BUF, "source"},
			{KOS_TYPE_BUF, "destination"},
			{KOS_TYPE_BUF, "copySize"},
		},
	},
	{
		.name = "wgpuCommandEncoderFinish",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "commandEncoder"},
			{KOS_TYPE_BUF, "descriptor"},
		},
	},
	{
		.name = "wgpuCommandEncoderInsertDebugMarker",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "commandEncoder"},
			{KOS_TYPE_OPAQUE_PTR, "markerLabel"},
		},
	},
	{
		.name = "wgpuCommandEncoderPopDebugGroup",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "commandEncoder"},
		},
	},
	{
		.name = "wgpuCommandEncoderPushDebugGroup",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "commandEncoder"},
			{KOS_TYPE_OPAQUE_PTR, "groupLabel"},
		},
	},
	{
		.name = "wgpuCommandEncoderResolveQuerySet",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 6,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "commandEncoder"},
			{KOS_TYPE_OPAQUE_PTR, "querySet"},
			{KOS_TYPE_U32, "firstQuery"},
			{KOS_TYPE_U32, "queryCount"},
			{KOS_TYPE_OPAQUE_PTR, "destination"},
			{KOS_TYPE_U64, "destinationOffset"},
		},
	},
	{
		.name = "wgpuCommandEncoderSetLabel",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "commandEncoder"},
			{KOS_TYPE_OPAQUE_PTR, "label"},
		},
	},
	{
		.name = "wgpuCommandEncoderWriteTimestamp",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 3,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "commandEncoder"},
			{KOS_TYPE_OPAQUE_PTR, "querySet"},
			{KOS_TYPE_U32, "queryIndex"},
		},
	},
	{
		.name = "wgpuCommandEncoderAddRef",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "commandEncoder"},
		},
	},
	{
		.name = "wgpuCommandEncoderRelease",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "commandEncoder"},
		},
	},
	{
		.name = "wgpuComputePassEncoderDispatchWorkgroups",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 4,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "computePassEncoder"},
			{KOS_TYPE_U32, "workgroupCountX"},
			{KOS_TYPE_U32, "workgroupCountY"},
			{KOS_TYPE_U32, "workgroupCountZ"},
		},
	},
	{
		.name = "wgpuComputePassEncoderDispatchWorkgroupsIndirect",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 3,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "computePassEncoder"},
			{KOS_TYPE_OPAQUE_PTR, "indirectBuffer"},
			{KOS_TYPE_U64, "indirectOffset"},
		},
	},
	{
		.name = "wgpuComputePassEncoderEnd",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "computePassEncoder"},
		},
	},
	{
		.name = "wgpuComputePassEncoderInsertDebugMarker",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "computePassEncoder"},
			{KOS_TYPE_OPAQUE_PTR, "markerLabel"},
		},
	},
	{
		.name = "wgpuComputePassEncoderPopDebugGroup",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "computePassEncoder"},
		},
	},
	{
		.name = "wgpuComputePassEncoderPushDebugGroup",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "computePassEncoder"},
			{KOS_TYPE_OPAQUE_PTR, "groupLabel"},
		},
	},
	{
		.name = "wgpuComputePassEncoderSetBindGroup",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 5,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "computePassEncoder"},
			{KOS_TYPE_U32, "groupIndex"},
			{KOS_TYPE_OPAQUE_PTR, "group"},
			{KOS_TYPE_U32, "dynamicOffsetCount"},
			{KOS_TYPE_BUF, "dynamicOffsets"},
		},
	},
	{
		.name = "wgpuComputePassEncoderSetLabel",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "computePassEncoder"},
			{KOS_TYPE_OPAQUE_PTR, "label"},
		},
	},
	{
		.name = "wgpuComputePassEncoderSetPipeline",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "computePassEncoder"},
			{KOS_TYPE_OPAQUE_PTR, "pipeline"},
		},
	},
	{
		.name = "wgpuComputePassEncoderAddRef",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "computePassEncoder"},
		},
	},
	{
		.name = "wgpuComputePassEncoderRelease",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "computePassEncoder"},
		},
	},
	{
		.name = "wgpuComputePipelineGetBindGroupLayout",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "computePipeline"},
			{KOS_TYPE_U32, "groupIndex"},
		},
	},
	{
		.name = "wgpuComputePipelineSetLabel",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "computePipeline"},
			{KOS_TYPE_OPAQUE_PTR, "label"},
		},
	},
	{
		.name = "wgpuComputePipelineAddRef",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "computePipeline"},
		},
	},
	{
		.name = "wgpuComputePipelineRelease",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "computePipeline"},
		},
	},
	{
		.name = "wgpuDeviceCreateBindGroup",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "device"},
			{KOS_TYPE_BUF, "descriptor"},
		},
	},
	{
		.name = "wgpuDeviceCreateBindGroupLayout",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "device"},
			{KOS_TYPE_BUF, "descriptor"},
		},
	},
	{
		.name = "wgpuDeviceCreateBuffer",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "device"},
			{KOS_TYPE_BUF, "descriptor"},
		},
	},
	{
		.name = "wgpuDeviceCreateCommandEncoder",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "device"},
			{KOS_TYPE_BUF, "descriptor"},
		},
	},
	{
		.name = "wgpuDeviceCreateComputePipeline",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "device"},
			{KOS_TYPE_BUF, "descriptor"},
		},
	},
	{
		.name = "wgpuDeviceCreateComputePipelineAsync",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 3,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "device"},
			{KOS_TYPE_BUF, "descriptor"},
			{KOS_TYPE_BUF, "callbackInfo"},
		},
	},
	{
		.name = "wgpuDeviceCreatePipelineLayout",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "device"},
			{KOS_TYPE_BUF, "descriptor"},
		},
	},
	{
		.name = "wgpuDeviceCreateQuerySet",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "device"},
			{KOS_TYPE_BUF, "descriptor"},
		},
	},
	{
		.name = "wgpuDeviceCreateRenderBundleEncoder",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "device"},
			{KOS_TYPE_BUF, "descriptor"},
		},
	},
	{
		.name = "wgpuDeviceCreateRenderPipeline",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "device"},
			{KOS_TYPE_BUF, "descriptor"},
		},
	},
	{
		.name = "wgpuDeviceCreateRenderPipelineAsync",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 3,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "device"},
			{KOS_TYPE_BUF, "descriptor"},
			{KOS_TYPE_BUF, "callbackInfo"},
		},
	},
	{
		.name = "wgpuDeviceCreateSampler",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "device"},
			{KOS_TYPE_BUF, "descriptor"},
		},
	},
	{
		.name = "wgpuDeviceCreateShaderModule",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "device"},
			{KOS_TYPE_BUF, "descriptor"},
		},
	},
	{
		.name = "wgpuDeviceCreateTexture",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "device"},
			{KOS_TYPE_BUF, "descriptor"},
		},
	},
	{
		.name = "wgpuDeviceDestroy",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "device"},
		},
	},
	{
		.name = "wgpuDeviceGetAdapterInfo",
		.ret_type = KOS_TYPE_BUF,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "device"},
		},
	},
	{
		.name = "wgpuDeviceGetFeatures",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "device"},
			{KOS_TYPE_BUF, "features"},
		},
	},
	{
		.name = "wgpuDeviceGetLimits",
		.ret_type = KOS_TYPE_U32,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "device"},
			{KOS_TYPE_BUF, "limits"},
		},
	},
	{
		.name = "wgpuDeviceGetLostFuture",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "device"},
		},
	},
	{
		.name = "wgpuDeviceGetQueue",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "device"},
		},
	},
	{
		.name = "wgpuDeviceHasFeature",
		.ret_type = KOS_TYPE_BOOL,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "device"},
			{KOS_TYPE_U32, "feature"},
		},
	},
	{
		.name = "wgpuDevicePopErrorScope",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "device"},
			{KOS_TYPE_BUF, "callbackInfo"},
		},
	},
	{
		.name = "wgpuDevicePushErrorScope",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "device"},
			{KOS_TYPE_U32, "filter"},
		},
	},
	{
		.name = "wgpuDeviceSetLabel",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "device"},
			{KOS_TYPE_OPAQUE_PTR, "label"},
		},
	},
	{
		.name = "wgpuDeviceAddRef",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "device"},
		},
	},
	{
		.name = "wgpuDeviceRelease",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "device"},
		},
	},
	{
		.name = "wgpuInstanceCreateSurface",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "instance"},
			{KOS_TYPE_BUF, "descriptor"},
		},
	},
	{
		.name = "wgpuInstanceGetWGSLLanguageFeatures",
		.ret_type = KOS_TYPE_U32,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "instance"},
			{KOS_TYPE_BUF, "features"},
		},
	},
	{
		.name = "wgpuInstanceProcessEvents",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "instance"},
		},
	},
	{
		.name = "wgpuInstanceRequestAdapter",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 3,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "instance"},
			{KOS_TYPE_BUF, "options"},
			{KOS_TYPE_BUF, "callbackInfo"},
		},
	},
	{
		.name = "wgpuInstanceWaitAny",
		.ret_type = KOS_TYPE_U32,
		.param_count = 4,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "instance"},
			{KOS_TYPE_U32, "futureCount"},
			{KOS_TYPE_BUF, "futures"},
			{KOS_TYPE_U64, "timeoutNS"},
		},
	},
	{
		.name = "wgpuInstanceAddRef",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "instance"},
		},
	},
	{
		.name = "wgpuInstanceRelease",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "instance"},
		},
	},
	{
		.name = "wgpuPipelineLayoutSetLabel",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "pipelineLayout"},
			{KOS_TYPE_OPAQUE_PTR, "label"},
		},
	},
	{
		.name = "wgpuPipelineLayoutAddRef",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "pipelineLayout"},
		},
	},
	{
		.name = "wgpuPipelineLayoutRelease",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "pipelineLayout"},
		},
	},
	{
		.name = "wgpuQuerySetDestroy",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "querySet"},
		},
	},
	{
		.name = "wgpuQuerySetGetCount",
		.ret_type = KOS_TYPE_U32,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "querySet"},
		},
	},
	{
		.name = "wgpuQuerySetGetType",
		.ret_type = KOS_TYPE_U32,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "querySet"},
		},
	},
	{
		.name = "wgpuQuerySetSetLabel",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "querySet"},
			{KOS_TYPE_OPAQUE_PTR, "label"},
		},
	},
	{
		.name = "wgpuQuerySetAddRef",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "querySet"},
		},
	},
	{
		.name = "wgpuQuerySetRelease",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "querySet"},
		},
	},
	{
		.name = "wgpuQueueOnSubmittedWorkDone",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "queue"},
			{KOS_TYPE_BUF, "callbackInfo"},
		},
	},
	{
		.name = "wgpuQueueSetLabel",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "queue"},
			{KOS_TYPE_OPAQUE_PTR, "label"},
		},
	},
	{
		.name = "wgpuQueueSubmit",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 3,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "queue"},
			{KOS_TYPE_U32, "commandCount"},
			{KOS_TYPE_BUF, "commands"},
		},
	},
	{
		.name = "wgpuQueueWriteBuffer",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 5,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "queue"},
			{KOS_TYPE_OPAQUE_PTR, "buffer"},
			{KOS_TYPE_U64, "bufferOffset"},
			{KOS_TYPE_OPAQUE_PTR, "data"},
			{KOS_TYPE_U32, "size"},
		},
	},
	{
		.name = "wgpuQueueWriteTexture",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 6,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "queue"},
			{KOS_TYPE_BUF, "destination"},
			{KOS_TYPE_OPAQUE_PTR, "data"},
			{KOS_TYPE_U32, "dataSize"},
			{KOS_TYPE_BUF, "dataLayout"},
			{KOS_TYPE_BUF, "writeSize"},
		},
	},
	{
		.name = "wgpuQueueAddRef",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "queue"},
		},
	},
	{
		.name = "wgpuQueueRelease",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "queue"},
		},
	},
	{
		.name = "wgpuRenderBundleSetLabel",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "renderBundle"},
			{KOS_TYPE_OPAQUE_PTR, "label"},
		},
	},
	{
		.name = "wgpuRenderBundleAddRef",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "renderBundle"},
		},
	},
	{
		.name = "wgpuRenderBundleRelease",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "renderBundle"},
		},
	},
	{
		.name = "wgpuRenderBundleEncoderDraw",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 5,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "renderBundleEncoder"},
			{KOS_TYPE_U32, "vertexCount"},
			{KOS_TYPE_U32, "instanceCount"},
			{KOS_TYPE_U32, "firstVertex"},
			{KOS_TYPE_U32, "firstInstance"},
		},
	},
	{
		.name = "wgpuRenderBundleEncoderDrawIndexed",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 6,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "renderBundleEncoder"},
			{KOS_TYPE_U32, "indexCount"},
			{KOS_TYPE_U32, "instanceCount"},
			{KOS_TYPE_U32, "firstIndex"},
			{KOS_TYPE_I32, "baseVertex"},
			{KOS_TYPE_U32, "firstInstance"},
		},
	},
	{
		.name = "wgpuRenderBundleEncoderDrawIndexedIndirect",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 3,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "renderBundleEncoder"},
			{KOS_TYPE_OPAQUE_PTR, "indirectBuffer"},
			{KOS_TYPE_U64, "indirectOffset"},
		},
	},
	{
		.name = "wgpuRenderBundleEncoderDrawIndirect",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 3,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "renderBundleEncoder"},
			{KOS_TYPE_OPAQUE_PTR, "indirectBuffer"},
			{KOS_TYPE_U64, "indirectOffset"},
		},
	},
	{
		.name = "wgpuRenderBundleEncoderFinish",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "renderBundleEncoder"},
			{KOS_TYPE_BUF, "descriptor"},
		},
	},
	{
		.name = "wgpuRenderBundleEncoderInsertDebugMarker",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "renderBundleEncoder"},
			{KOS_TYPE_OPAQUE_PTR, "markerLabel"},
		},
	},
	{
		.name = "wgpuRenderBundleEncoderPopDebugGroup",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "renderBundleEncoder"},
		},
	},
	{
		.name = "wgpuRenderBundleEncoderPushDebugGroup",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "renderBundleEncoder"},
			{KOS_TYPE_OPAQUE_PTR, "groupLabel"},
		},
	},
	{
		.name = "wgpuRenderBundleEncoderSetBindGroup",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 5,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "renderBundleEncoder"},
			{KOS_TYPE_U32, "groupIndex"},
			{KOS_TYPE_OPAQUE_PTR, "group"},
			{KOS_TYPE_U32, "dynamicOffsetCount"},
			{KOS_TYPE_BUF, "dynamicOffsets"},
		},
	},
	{
		.name = "wgpuRenderBundleEncoderSetIndexBuffer",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 5,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "renderBundleEncoder"},
			{KOS_TYPE_OPAQUE_PTR, "buffer"},
			{KOS_TYPE_U32, "format"},
			{KOS_TYPE_U64, "offset"},
			{KOS_TYPE_U64, "size"},
		},
	},
	{
		.name = "wgpuRenderBundleEncoderSetLabel",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "renderBundleEncoder"},
			{KOS_TYPE_OPAQUE_PTR, "label"},
		},
	},
	{
		.name = "wgpuRenderBundleEncoderSetPipeline",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "renderBundleEncoder"},
			{KOS_TYPE_OPAQUE_PTR, "pipeline"},
		},
	},
	{
		.name = "wgpuRenderBundleEncoderSetVertexBuffer",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 5,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "renderBundleEncoder"},
			{KOS_TYPE_U32, "slot"},
			{KOS_TYPE_OPAQUE_PTR, "buffer"},
			{KOS_TYPE_U64, "offset"},
			{KOS_TYPE_U64, "size"},
		},
	},
	{
		.name = "wgpuRenderBundleEncoderAddRef",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "renderBundleEncoder"},
		},
	},
	{
		.name = "wgpuRenderBundleEncoderRelease",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "renderBundleEncoder"},
		},
	},
	{
		.name = "wgpuRenderPassEncoderBeginOcclusionQuery",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "renderPassEncoder"},
			{KOS_TYPE_U32, "queryIndex"},
		},
	},
	{
		.name = "wgpuRenderPassEncoderDraw",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 5,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "renderPassEncoder"},
			{KOS_TYPE_U32, "vertexCount"},
			{KOS_TYPE_U32, "instanceCount"},
			{KOS_TYPE_U32, "firstVertex"},
			{KOS_TYPE_U32, "firstInstance"},
		},
	},
	{
		.name = "wgpuRenderPassEncoderDrawIndexed",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 6,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "renderPassEncoder"},
			{KOS_TYPE_U32, "indexCount"},
			{KOS_TYPE_U32, "instanceCount"},
			{KOS_TYPE_U32, "firstIndex"},
			{KOS_TYPE_I32, "baseVertex"},
			{KOS_TYPE_U32, "firstInstance"},
		},
	},
	{
		.name = "wgpuRenderPassEncoderDrawIndexedIndirect",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 3,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "renderPassEncoder"},
			{KOS_TYPE_OPAQUE_PTR, "indirectBuffer"},
			{KOS_TYPE_U64, "indirectOffset"},
		},
	},
	{
		.name = "wgpuRenderPassEncoderDrawIndirect",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 3,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "renderPassEncoder"},
			{KOS_TYPE_OPAQUE_PTR, "indirectBuffer"},
			{KOS_TYPE_U64, "indirectOffset"},
		},
	},
	{
		.name = "wgpuRenderPassEncoderEnd",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "renderPassEncoder"},
		},
	},
	{
		.name = "wgpuRenderPassEncoderEndOcclusionQuery",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "renderPassEncoder"},
		},
	},
	{
		.name = "wgpuRenderPassEncoderExecuteBundles",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 3,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "renderPassEncoder"},
			{KOS_TYPE_U32, "bundleCount"},
			{KOS_TYPE_BUF, "bundles"},
		},
	},
	{
		.name = "wgpuRenderPassEncoderInsertDebugMarker",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "renderPassEncoder"},
			{KOS_TYPE_OPAQUE_PTR, "markerLabel"},
		},
	},
	{
		.name = "wgpuRenderPassEncoderPopDebugGroup",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "renderPassEncoder"},
		},
	},
	{
		.name = "wgpuRenderPassEncoderPushDebugGroup",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "renderPassEncoder"},
			{KOS_TYPE_OPAQUE_PTR, "groupLabel"},
		},
	},
	{
		.name = "wgpuRenderPassEncoderSetBindGroup",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 5,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "renderPassEncoder"},
			{KOS_TYPE_U32, "groupIndex"},
			{KOS_TYPE_OPAQUE_PTR, "group"},
			{KOS_TYPE_U32, "dynamicOffsetCount"},
			{KOS_TYPE_BUF, "dynamicOffsets"},
		},
	},
	{
		.name = "wgpuRenderPassEncoderSetBlendConstant",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "renderPassEncoder"},
			{KOS_TYPE_BUF, "color"},
		},
	},
	{
		.name = "wgpuRenderPassEncoderSetIndexBuffer",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 5,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "renderPassEncoder"},
			{KOS_TYPE_OPAQUE_PTR, "buffer"},
			{KOS_TYPE_U32, "format"},
			{KOS_TYPE_U64, "offset"},
			{KOS_TYPE_U64, "size"},
		},
	},
	{
		.name = "wgpuRenderPassEncoderSetLabel",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "renderPassEncoder"},
			{KOS_TYPE_OPAQUE_PTR, "label"},
		},
	},
	{
		.name = "wgpuRenderPassEncoderSetPipeline",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "renderPassEncoder"},
			{KOS_TYPE_OPAQUE_PTR, "pipeline"},
		},
	},
	{
		.name = "wgpuRenderPassEncoderSetScissorRect",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 5,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "renderPassEncoder"},
			{KOS_TYPE_U32, "x"},
			{KOS_TYPE_U32, "y"},
			{KOS_TYPE_U32, "width"},
			{KOS_TYPE_U32, "height"},
		},
	},
	{
		.name = "wgpuRenderPassEncoderSetStencilReference",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "renderPassEncoder"},
			{KOS_TYPE_U32, "reference"},
		},
	},
	{
		.name = "wgpuRenderPassEncoderSetVertexBuffer",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 5,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "renderPassEncoder"},
			{KOS_TYPE_U32, "slot"},
			{KOS_TYPE_OPAQUE_PTR, "buffer"},
			{KOS_TYPE_U64, "offset"},
			{KOS_TYPE_U64, "size"},
		},
	},
	{
		.name = "wgpuRenderPassEncoderSetViewport",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 7,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "renderPassEncoder"},
			{KOS_TYPE_F32, "x"},
			{KOS_TYPE_F32, "y"},
			{KOS_TYPE_F32, "width"},
			{KOS_TYPE_F32, "height"},
			{KOS_TYPE_F32, "minDepth"},
			{KOS_TYPE_F32, "maxDepth"},
		},
	},
	{
		.name = "wgpuRenderPassEncoderAddRef",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "renderPassEncoder"},
		},
	},
	{
		.name = "wgpuRenderPassEncoderRelease",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "renderPassEncoder"},
		},
	},
	{
		.name = "wgpuRenderPipelineGetBindGroupLayout",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "renderPipeline"},
			{KOS_TYPE_U32, "groupIndex"},
		},
	},
	{
		.name = "wgpuRenderPipelineSetLabel",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "renderPipeline"},
			{KOS_TYPE_OPAQUE_PTR, "label"},
		},
	},
	{
		.name = "wgpuRenderPipelineAddRef",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "renderPipeline"},
		},
	},
	{
		.name = "wgpuRenderPipelineRelease",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "renderPipeline"},
		},
	},
	{
		.name = "wgpuSamplerSetLabel",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "sampler"},
			{KOS_TYPE_OPAQUE_PTR, "label"},
		},
	},
	{
		.name = "wgpuSamplerAddRef",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "sampler"},
		},
	},
	{
		.name = "wgpuSamplerRelease",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "sampler"},
		},
	},
	{
		.name = "wgpuShaderModuleGetCompilationInfo",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "shaderModule"},
			{KOS_TYPE_BUF, "callbackInfo"},
		},
	},
	{
		.name = "wgpuShaderModuleSetLabel",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "shaderModule"},
			{KOS_TYPE_OPAQUE_PTR, "label"},
		},
	},
	{
		.name = "wgpuShaderModuleAddRef",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "shaderModule"},
		},
	},
	{
		.name = "wgpuShaderModuleRelease",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "shaderModule"},
		},
	},
	{
		.name = "wgpuSupportedFeaturesFreeMembers",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_BUF, "supportedFeatures"},
		},
	},
	{
		.name = "wgpuSupportedWGSLLanguageFeaturesFreeMembers",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_BUF, "supportedWGSLLanguageFeatures"},
		},
	},
	{
		.name = "wgpuSurfaceConfigure",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "surface"},
			{KOS_TYPE_BUF, "config"},
		},
	},
	{
		.name = "wgpuSurfaceGetCapabilities",
		.ret_type = KOS_TYPE_U32,
		.param_count = 3,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "surface"},
			{KOS_TYPE_OPAQUE_PTR, "adapter"},
			{KOS_TYPE_BUF, "capabilities"},
		},
	},
	{
		.name = "wgpuSurfaceGetCurrentTexture",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "surface"},
			{KOS_TYPE_BUF, "surfaceTexture"},
		},
	},
	{
		.name = "wgpuSurfacePresent",
		.ret_type = KOS_TYPE_U32,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "surface"},
		},
	},
	{
		.name = "wgpuSurfaceUnconfigure",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "surface"},
		},
	},
	{
		.name = "wgpuSurfaceAddRef",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "surface"},
		},
	},
	{
		.name = "wgpuSurfaceRelease",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "surface"},
		},
	},
	{
		.name = "wgpuSurfaceCapabilitiesFreeMembers",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_BUF, "surfaceCapabilities"},
		},
	},
	{
		.name = "wgpuTextureCreateView",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "texture"},
			{KOS_TYPE_BUF, "descriptor"},
		},
	},
	{
		.name = "wgpuTextureDestroy",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "texture"},
		},
	},
	{
		.name = "wgpuTextureGetDepthOrArrayLayers",
		.ret_type = KOS_TYPE_U32,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "texture"},
		},
	},
	{
		.name = "wgpuTextureGetDimension",
		.ret_type = KOS_TYPE_U32,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "texture"},
		},
	},
	{
		.name = "wgpuTextureGetFormat",
		.ret_type = KOS_TYPE_U32,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "texture"},
		},
	},
	{
		.name = "wgpuTextureGetHeight",
		.ret_type = KOS_TYPE_U32,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "texture"},
		},
	},
	{
		.name = "wgpuTextureGetMipLevelCount",
		.ret_type = KOS_TYPE_U32,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "texture"},
		},
	},
	{
		.name = "wgpuTextureGetSampleCount",
		.ret_type = KOS_TYPE_U32,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "texture"},
		},
	},
	{
		.name = "wgpuTextureGetUsage",
		.ret_type = KOS_TYPE_U64,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "texture"},
		},
	},
	{
		.name = "wgpuTextureGetWidth",
		.ret_type = KOS_TYPE_U32,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "texture"},
		},
	},
	{
		.name = "wgpuTextureSetLabel",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "texture"},
			{KOS_TYPE_OPAQUE_PTR, "label"},
		},
	},
	{
		.name = "wgpuTextureAddRef",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "texture"},
		},
	},
	{
		.name = "wgpuTextureRelease",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "texture"},
		},
	},
	{
		.name = "wgpuTextureViewSetLabel",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "textureView"},
			{KOS_TYPE_OPAQUE_PTR, "label"},
		},
	},
	{
		.name = "wgpuTextureViewAddRef",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "textureView"},
		},
	},
	{
		.name = "wgpuTextureViewRelease",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "textureView"},
		},
	},
	{
		.name = "wgpuGenerateReport",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "instance"},
			{KOS_TYPE_BUF, "report"},
		},
	},
	{
		.name = "wgpuInstanceEnumerateAdapters",
		.ret_type = KOS_TYPE_U32,
		.param_count = 3,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "instance"},
			{KOS_TYPE_BUF, "options"},
			{KOS_TYPE_BUF, "adapters"},
		},
	},
	{
		.name = "wgpuQueueSubmitForIndex",
		.ret_type = KOS_TYPE_U64,
		.param_count = 3,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "queue"},
			{KOS_TYPE_U32, "commandCount"},
			{KOS_TYPE_BUF, "commands"},
		},
	},
	{
		.name = "wgpuDevicePoll",
		.ret_type = KOS_TYPE_BOOL,
		.param_count = 3,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "device"},
			{KOS_TYPE_BOOL, "wait"},
			{KOS_TYPE_BUF, "submissionIndex"},
		},
	},
	{
		.name = "wgpuDeviceCreateShaderModuleSpirV",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "device"},
			{KOS_TYPE_BUF, "descriptor"},
		},
	},
	{
		.name = "wgpuSetLogCallback",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "callback"},
			{KOS_TYPE_OPAQUE_PTR, "userdata"},
		},
	},
	{
		.name = "wgpuSetLogLevel",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_U32, "level"},
		},
	},
	{
		.name = "wgpuGetVersion",
		.ret_type = KOS_TYPE_U32,
		.param_count = 0,
		.params = (kos_param_t[]) {
		},
	},
	{
		.name = "wgpuRenderPassEncoderSetPushConstants",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 5,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "encoder"},
			{KOS_TYPE_U64, "stages"},
			{KOS_TYPE_U32, "offset"},
			{KOS_TYPE_U32, "sizeBytes"},
			{KOS_TYPE_OPAQUE_PTR, "data"},
		},
	},
	{
		.name = "wgpuComputePassEncoderSetPushConstants",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 4,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "encoder"},
			{KOS_TYPE_U32, "offset"},
			{KOS_TYPE_U32, "sizeBytes"},
			{KOS_TYPE_OPAQUE_PTR, "data"},
		},
	},
	{
		.name = "wgpuRenderBundleEncoderSetPushConstants",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 5,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "encoder"},
			{KOS_TYPE_U64, "stages"},
			{KOS_TYPE_U32, "offset"},
			{KOS_TYPE_U32, "sizeBytes"},
			{KOS_TYPE_OPAQUE_PTR, "data"},
		},
	},
	{
		.name = "wgpuRenderPassEncoderMultiDrawIndirect",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 4,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "encoder"},
			{KOS_TYPE_OPAQUE_PTR, "buffer"},
			{KOS_TYPE_U64, "offset"},
			{KOS_TYPE_U32, "count"},
		},
	},
	{
		.name = "wgpuRenderPassEncoderMultiDrawIndexedIndirect",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 4,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "encoder"},
			{KOS_TYPE_OPAQUE_PTR, "buffer"},
			{KOS_TYPE_U64, "offset"},
			{KOS_TYPE_U32, "count"},
		},
	},
	{
		.name = "wgpuRenderPassEncoderMultiDrawIndirectCount",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 6,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "encoder"},
			{KOS_TYPE_OPAQUE_PTR, "buffer"},
			{KOS_TYPE_U64, "offset"},
			{KOS_TYPE_OPAQUE_PTR, "count_buffer"},
			{KOS_TYPE_U64, "count_buffer_offset"},
			{KOS_TYPE_U32, "max_count"},
		},
	},
	{
		.name = "wgpuRenderPassEncoderMultiDrawIndexedIndirectCount",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 6,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "encoder"},
			{KOS_TYPE_OPAQUE_PTR, "buffer"},
			{KOS_TYPE_U64, "offset"},
			{KOS_TYPE_OPAQUE_PTR, "count_buffer"},
			{KOS_TYPE_U64, "count_buffer_offset"},
			{KOS_TYPE_U32, "max_count"},
		},
	},
	{
		.name = "wgpuComputePassEncoderBeginPipelineStatisticsQuery",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 3,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "computePassEncoder"},
			{KOS_TYPE_OPAQUE_PTR, "querySet"},
			{KOS_TYPE_U32, "queryIndex"},
		},
	},
	{
		.name = "wgpuComputePassEncoderEndPipelineStatisticsQuery",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "computePassEncoder"},
		},
	},
	{
		.name = "wgpuRenderPassEncoderBeginPipelineStatisticsQuery",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 3,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "renderPassEncoder"},
			{KOS_TYPE_OPAQUE_PTR, "querySet"},
			{KOS_TYPE_U32, "queryIndex"},
		},
	},
	{
		.name = "wgpuRenderPassEncoderEndPipelineStatisticsQuery",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "renderPassEncoder"},
		},
	},
	{
		.name = "wgpuComputePassEncoderWriteTimestamp",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 3,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "computePassEncoder"},
			{KOS_TYPE_OPAQUE_PTR, "querySet"},
			{KOS_TYPE_U32, "queryIndex"},
		},
	},
	{
		.name = "wgpuRenderPassEncoderWriteTimestamp",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 3,
		.params = (kos_param_t[]) {
			{KOS_TYPE_OPAQUE_PTR, "renderPassEncoder"},
			{KOS_TYPE_OPAQUE_PTR, "querySet"},
			{KOS_TYPE_U32, "queryIndex"},
		},
	},
// FNS:END
	// clang-format on
};
