// This Source Form is subject to the terms of the AQUA Software License, v. 1.0.
// Copyright (c) 2025 Aymeric Wibo

#include "../../kos/vdev.h"

static kos_fn_t const FNS[] = {
	{
		.name = "surface_from_win",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "instance",
			},
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "win",
			},
		},
	},

	// This file is automatically generated by 'vdev/wgpu/gen.py'.
	// If you need to update this, read the 'vdev/wgpu/README.md' document.

	// clang-format off
// FNS:BEGIN
	{
		.name = "wgpuCreateInstance",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_BUF,
				.name = "descriptor",
			},
		},
	},
	{
		.name = "wgpuGetInstanceCapabilities",
		.ret_type = KOS_TYPE_U32,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_BUF,
				.name = "capabilities",
			},
		},
	},
	{
		.name = "wgpuGetProcAddress",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "procName",
			},
		},
	},
	{
		.name = "wgpuAdapterGetFeatures",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "adapter",
			},
			{
				.type = KOS_TYPE_BUF,
				.name = "features",
			},
		},
	},
	{
		.name = "wgpuAdapterGetInfo",
		.ret_type = KOS_TYPE_U32,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "adapter",
			},
			{
				.type = KOS_TYPE_BUF,
				.name = "info",
			},
		},
	},
	{
		.name = "wgpuAdapterGetLimits",
		.ret_type = KOS_TYPE_U32,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "adapter",
			},
			{
				.type = KOS_TYPE_BUF,
				.name = "limits",
			},
		},
	},
	{
		.name = "wgpuAdapterHasFeature",
		.ret_type = KOS_TYPE_BOOL,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "adapter",
			},
			{
				.type = KOS_TYPE_U32,
				.name = "feature",
			},
		},
	},
	{
		.name = "wgpuAdapterRequestDevice",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 3,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "adapter",
			},
			{
				.type = KOS_TYPE_BUF,
				.name = "descriptor",
			},
			{
				.type = KOS_TYPE_BUF,
				.name = "callbackInfo",
			},
		},
	},
	{
		.name = "wgpuAdapterAddRef",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "adapter",
			},
		},
	},
	{
		.name = "wgpuAdapterRelease",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "adapter",
			},
		},
	},
	{
		.name = "wgpuAdapterInfoFreeMembers",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "adapterInfo",
			},
		},
	},
	{
		.name = "wgpuBindGroupSetLabel",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "bindGroup",
			},
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "label",
			},
		},
	},
	{
		.name = "wgpuBindGroupAddRef",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "bindGroup",
			},
		},
	},
	{
		.name = "wgpuBindGroupRelease",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "bindGroup",
			},
		},
	},
	{
		.name = "wgpuBindGroupLayoutSetLabel",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "bindGroupLayout",
			},
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "label",
			},
		},
	},
	{
		.name = "wgpuBindGroupLayoutAddRef",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "bindGroupLayout",
			},
		},
	},
	{
		.name = "wgpuBindGroupLayoutRelease",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "bindGroupLayout",
			},
		},
	},
	{
		.name = "wgpuBufferDestroy",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "buffer",
			},
		},
	},
	{
		.name = "wgpuBufferGetConstMappedRange",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 3,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "buffer",
			},
			{
				.type = KOS_TYPE_U32,
				.name = "offset",
			},
			{
				.type = KOS_TYPE_U32,
				.name = "size",
			},
		},
	},
	{
		.name = "wgpuBufferGetMapState",
		.ret_type = KOS_TYPE_U32,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "buffer",
			},
		},
	},
	{
		.name = "wgpuBufferGetMappedRange",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 3,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "buffer",
			},
			{
				.type = KOS_TYPE_U32,
				.name = "offset",
			},
			{
				.type = KOS_TYPE_U32,
				.name = "size",
			},
		},
	},
	{
		.name = "wgpuBufferGetSize",
		.ret_type = KOS_TYPE_U64,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "buffer",
			},
		},
	},
	{
		.name = "wgpuBufferGetUsage",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "buffer",
			},
		},
	},
	{
		.name = "wgpuBufferMapAsync",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 5,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "buffer",
			},
			{
				.type = KOS_TYPE_U64,
				.name = "mode",
			},
			{
				.type = KOS_TYPE_U32,
				.name = "offset",
			},
			{
				.type = KOS_TYPE_U32,
				.name = "size",
			},
			{
				.type = KOS_TYPE_BUF,
				.name = "callbackInfo",
			},
		},
	},
	{
		.name = "wgpuBufferSetLabel",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "buffer",
			},
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "label",
			},
		},
	},
	{
		.name = "wgpuBufferUnmap",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "buffer",
			},
		},
	},
	{
		.name = "wgpuBufferAddRef",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "buffer",
			},
		},
	},
	{
		.name = "wgpuBufferRelease",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "buffer",
			},
		},
	},
	{
		.name = "wgpuCommandBufferSetLabel",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "commandBuffer",
			},
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "label",
			},
		},
	},
	{
		.name = "wgpuCommandBufferAddRef",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "commandBuffer",
			},
		},
	},
	{
		.name = "wgpuCommandBufferRelease",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "commandBuffer",
			},
		},
	},
	{
		.name = "wgpuCommandEncoderBeginComputePass",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "commandEncoder",
			},
			{
				.type = KOS_TYPE_BUF,
				.name = "descriptor",
			},
		},
	},
	{
		.name = "wgpuCommandEncoderBeginRenderPass",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "commandEncoder",
			},
			{
				.type = KOS_TYPE_BUF,
				.name = "descriptor",
			},
		},
	},
	{
		.name = "wgpuCommandEncoderClearBuffer",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 4,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "commandEncoder",
			},
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "buffer",
			},
			{
				.type = KOS_TYPE_U64,
				.name = "offset",
			},
			{
				.type = KOS_TYPE_U64,
				.name = "size",
			},
		},
	},
	{
		.name = "wgpuCommandEncoderCopyBufferToBuffer",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 6,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "commandEncoder",
			},
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "source",
			},
			{
				.type = KOS_TYPE_U64,
				.name = "sourceOffset",
			},
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "destination",
			},
			{
				.type = KOS_TYPE_U64,
				.name = "destinationOffset",
			},
			{
				.type = KOS_TYPE_U64,
				.name = "size",
			},
		},
	},
	{
		.name = "wgpuCommandEncoderCopyBufferToTexture",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 4,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "commandEncoder",
			},
			{
				.type = KOS_TYPE_BUF,
				.name = "source",
			},
			{
				.type = KOS_TYPE_BUF,
				.name = "destination",
			},
			{
				.type = KOS_TYPE_BUF,
				.name = "copySize",
			},
		},
	},
	{
		.name = "wgpuCommandEncoderCopyTextureToBuffer",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 4,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "commandEncoder",
			},
			{
				.type = KOS_TYPE_BUF,
				.name = "source",
			},
			{
				.type = KOS_TYPE_BUF,
				.name = "destination",
			},
			{
				.type = KOS_TYPE_BUF,
				.name = "copySize",
			},
		},
	},
	{
		.name = "wgpuCommandEncoderCopyTextureToTexture",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 4,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "commandEncoder",
			},
			{
				.type = KOS_TYPE_BUF,
				.name = "source",
			},
			{
				.type = KOS_TYPE_BUF,
				.name = "destination",
			},
			{
				.type = KOS_TYPE_BUF,
				.name = "copySize",
			},
		},
	},
	{
		.name = "wgpuCommandEncoderFinish",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "commandEncoder",
			},
			{
				.type = KOS_TYPE_BUF,
				.name = "descriptor",
			},
		},
	},
	{
		.name = "wgpuCommandEncoderInsertDebugMarker",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "commandEncoder",
			},
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "markerLabel",
			},
		},
	},
	{
		.name = "wgpuCommandEncoderPopDebugGroup",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "commandEncoder",
			},
		},
	},
	{
		.name = "wgpuCommandEncoderPushDebugGroup",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "commandEncoder",
			},
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "groupLabel",
			},
		},
	},
	{
		.name = "wgpuCommandEncoderResolveQuerySet",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 6,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "commandEncoder",
			},
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "querySet",
			},
			{
				.type = KOS_TYPE_U32,
				.name = "firstQuery",
			},
			{
				.type = KOS_TYPE_U32,
				.name = "queryCount",
			},
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "destination",
			},
			{
				.type = KOS_TYPE_U64,
				.name = "destinationOffset",
			},
		},
	},
	{
		.name = "wgpuCommandEncoderSetLabel",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "commandEncoder",
			},
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "label",
			},
		},
	},
	{
		.name = "wgpuCommandEncoderWriteTimestamp",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 3,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "commandEncoder",
			},
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "querySet",
			},
			{
				.type = KOS_TYPE_U32,
				.name = "queryIndex",
			},
		},
	},
	{
		.name = "wgpuCommandEncoderAddRef",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "commandEncoder",
			},
		},
	},
	{
		.name = "wgpuCommandEncoderRelease",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "commandEncoder",
			},
		},
	},
	{
		.name = "wgpuComputePassEncoderDispatchWorkgroups",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 4,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "computePassEncoder",
			},
			{
				.type = KOS_TYPE_U32,
				.name = "workgroupCountX",
			},
			{
				.type = KOS_TYPE_U32,
				.name = "workgroupCountY",
			},
			{
				.type = KOS_TYPE_U32,
				.name = "workgroupCountZ",
			},
		},
	},
	{
		.name = "wgpuComputePassEncoderDispatchWorkgroupsIndirect",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 3,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "computePassEncoder",
			},
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "indirectBuffer",
			},
			{
				.type = KOS_TYPE_U64,
				.name = "indirectOffset",
			},
		},
	},
	{
		.name = "wgpuComputePassEncoderEnd",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "computePassEncoder",
			},
		},
	},
	{
		.name = "wgpuComputePassEncoderInsertDebugMarker",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "computePassEncoder",
			},
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "markerLabel",
			},
		},
	},
	{
		.name = "wgpuComputePassEncoderPopDebugGroup",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "computePassEncoder",
			},
		},
	},
	{
		.name = "wgpuComputePassEncoderPushDebugGroup",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "computePassEncoder",
			},
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "groupLabel",
			},
		},
	},
	{
		.name = "wgpuComputePassEncoderSetBindGroup",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 5,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "computePassEncoder",
			},
			{
				.type = KOS_TYPE_U32,
				.name = "groupIndex",
			},
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "group",
			},
			{
				.type = KOS_TYPE_U32,
				.name = "dynamicOffsetCount",
			},
			{
				.type = KOS_TYPE_BUF,
				.name = "dynamicOffsets",
			},
		},
	},
	{
		.name = "wgpuComputePassEncoderSetLabel",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "computePassEncoder",
			},
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "label",
			},
		},
	},
	{
		.name = "wgpuComputePassEncoderSetPipeline",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "computePassEncoder",
			},
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "pipeline",
			},
		},
	},
	{
		.name = "wgpuComputePassEncoderAddRef",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "computePassEncoder",
			},
		},
	},
	{
		.name = "wgpuComputePassEncoderRelease",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "computePassEncoder",
			},
		},
	},
	{
		.name = "wgpuComputePipelineGetBindGroupLayout",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "computePipeline",
			},
			{
				.type = KOS_TYPE_U32,
				.name = "groupIndex",
			},
		},
	},
	{
		.name = "wgpuComputePipelineSetLabel",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "computePipeline",
			},
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "label",
			},
		},
	},
	{
		.name = "wgpuComputePipelineAddRef",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "computePipeline",
			},
		},
	},
	{
		.name = "wgpuComputePipelineRelease",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "computePipeline",
			},
		},
	},
	{
		.name = "wgpuDeviceCreateBindGroup",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "device",
			},
			{
				.type = KOS_TYPE_BUF,
				.name = "descriptor",
			},
		},
	},
	{
		.name = "wgpuDeviceCreateBindGroupLayout",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "device",
			},
			{
				.type = KOS_TYPE_BUF,
				.name = "descriptor",
			},
		},
	},
	{
		.name = "wgpuDeviceCreateBuffer",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "device",
			},
			{
				.type = KOS_TYPE_BUF,
				.name = "descriptor",
			},
		},
	},
	{
		.name = "wgpuDeviceCreateCommandEncoder",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "device",
			},
			{
				.type = KOS_TYPE_BUF,
				.name = "descriptor",
			},
		},
	},
	{
		.name = "wgpuDeviceCreateComputePipeline",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "device",
			},
			{
				.type = KOS_TYPE_BUF,
				.name = "descriptor",
			},
		},
	},
	{
		.name = "wgpuDeviceCreateComputePipelineAsync",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 3,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "device",
			},
			{
				.type = KOS_TYPE_BUF,
				.name = "descriptor",
			},
			{
				.type = KOS_TYPE_BUF,
				.name = "callbackInfo",
			},
		},
	},
	{
		.name = "wgpuDeviceCreatePipelineLayout",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "device",
			},
			{
				.type = KOS_TYPE_BUF,
				.name = "descriptor",
			},
		},
	},
	{
		.name = "wgpuDeviceCreateQuerySet",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "device",
			},
			{
				.type = KOS_TYPE_BUF,
				.name = "descriptor",
			},
		},
	},
	{
		.name = "wgpuDeviceCreateRenderBundleEncoder",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "device",
			},
			{
				.type = KOS_TYPE_BUF,
				.name = "descriptor",
			},
		},
	},
	{
		.name = "wgpuDeviceCreateRenderPipeline",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "device",
			},
			{
				.type = KOS_TYPE_BUF,
				.name = "descriptor",
			},
		},
	},
	{
		.name = "wgpuDeviceCreateRenderPipelineAsync",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 3,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "device",
			},
			{
				.type = KOS_TYPE_BUF,
				.name = "descriptor",
			},
			{
				.type = KOS_TYPE_BUF,
				.name = "callbackInfo",
			},
		},
	},
	{
		.name = "wgpuDeviceCreateSampler",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "device",
			},
			{
				.type = KOS_TYPE_BUF,
				.name = "descriptor",
			},
		},
	},
	{
		.name = "wgpuDeviceCreateShaderModule",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "device",
			},
			{
				.type = KOS_TYPE_BUF,
				.name = "descriptor",
			},
		},
	},
	{
		.name = "wgpuDeviceCreateTexture",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "device",
			},
			{
				.type = KOS_TYPE_BUF,
				.name = "descriptor",
			},
		},
	},
	{
		.name = "wgpuDeviceDestroy",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "device",
			},
		},
	},
	{
		.name = "wgpuDeviceGetAdapterInfo",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "device",
			},
		},
	},
	{
		.name = "wgpuDeviceGetFeatures",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "device",
			},
			{
				.type = KOS_TYPE_BUF,
				.name = "features",
			},
		},
	},
	{
		.name = "wgpuDeviceGetLimits",
		.ret_type = KOS_TYPE_U32,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "device",
			},
			{
				.type = KOS_TYPE_BUF,
				.name = "limits",
			},
		},
	},
	{
		.name = "wgpuDeviceGetLostFuture",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "device",
			},
		},
	},
	{
		.name = "wgpuDeviceGetQueue",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "device",
			},
		},
	},
	{
		.name = "wgpuDeviceHasFeature",
		.ret_type = KOS_TYPE_BOOL,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "device",
			},
			{
				.type = KOS_TYPE_U32,
				.name = "feature",
			},
		},
	},
	{
		.name = "wgpuDevicePopErrorScope",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "device",
			},
			{
				.type = KOS_TYPE_BUF,
				.name = "callbackInfo",
			},
		},
	},
	{
		.name = "wgpuDevicePushErrorScope",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "device",
			},
			{
				.type = KOS_TYPE_U32,
				.name = "filter",
			},
		},
	},
	{
		.name = "wgpuDeviceSetLabel",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "device",
			},
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "label",
			},
		},
	},
	{
		.name = "wgpuDeviceAddRef",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "device",
			},
		},
	},
	{
		.name = "wgpuDeviceRelease",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "device",
			},
		},
	},
	{
		.name = "wgpuInstanceCreateSurface",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "instance",
			},
			{
				.type = KOS_TYPE_BUF,
				.name = "descriptor",
			},
		},
	},
	{
		.name = "wgpuInstanceGetWGSLLanguageFeatures",
		.ret_type = KOS_TYPE_U32,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "instance",
			},
			{
				.type = KOS_TYPE_BUF,
				.name = "features",
			},
		},
	},
	{
		.name = "wgpuInstanceProcessEvents",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "instance",
			},
		},
	},
	{
		.name = "wgpuInstanceRequestAdapter",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 3,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "instance",
			},
			{
				.type = KOS_TYPE_BUF,
				.name = "options",
			},
			{
				.type = KOS_TYPE_BUF,
				.name = "callbackInfo",
			},
		},
	},
	{
		.name = "wgpuInstanceWaitAny",
		.ret_type = KOS_TYPE_U32,
		.param_count = 4,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "instance",
			},
			{
				.type = KOS_TYPE_U32,
				.name = "futureCount",
			},
			{
				.type = KOS_TYPE_BUF,
				.name = "futures",
			},
			{
				.type = KOS_TYPE_U64,
				.name = "timeoutNS",
			},
		},
	},
	{
		.name = "wgpuInstanceAddRef",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "instance",
			},
		},
	},
	{
		.name = "wgpuInstanceRelease",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "instance",
			},
		},
	},
	{
		.name = "wgpuPipelineLayoutSetLabel",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "pipelineLayout",
			},
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "label",
			},
		},
	},
	{
		.name = "wgpuPipelineLayoutAddRef",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "pipelineLayout",
			},
		},
	},
	{
		.name = "wgpuPipelineLayoutRelease",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "pipelineLayout",
			},
		},
	},
	{
		.name = "wgpuQuerySetDestroy",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "querySet",
			},
		},
	},
	{
		.name = "wgpuQuerySetGetCount",
		.ret_type = KOS_TYPE_U32,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "querySet",
			},
		},
	},
	{
		.name = "wgpuQuerySetGetType",
		.ret_type = KOS_TYPE_U32,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "querySet",
			},
		},
	},
	{
		.name = "wgpuQuerySetSetLabel",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "querySet",
			},
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "label",
			},
		},
	},
	{
		.name = "wgpuQuerySetAddRef",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "querySet",
			},
		},
	},
	{
		.name = "wgpuQuerySetRelease",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "querySet",
			},
		},
	},
	{
		.name = "wgpuQueueOnSubmittedWorkDone",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "queue",
			},
			{
				.type = KOS_TYPE_BUF,
				.name = "callbackInfo",
			},
		},
	},
	{
		.name = "wgpuQueueSetLabel",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "queue",
			},
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "label",
			},
		},
	},
	{
		.name = "wgpuQueueSubmit",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 3,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "queue",
			},
			{
				.type = KOS_TYPE_U32,
				.name = "commandCount",
			},
			{
				.type = KOS_TYPE_BUF,
				.name = "commands",
			},
		},
	},
	{
		.name = "wgpuQueueWriteBuffer",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 5,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "queue",
			},
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "buffer",
			},
			{
				.type = KOS_TYPE_U64,
				.name = "bufferOffset",
			},
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "data",
			},
			{
				.type = KOS_TYPE_U32,
				.name = "size",
			},
		},
	},
	{
		.name = "wgpuQueueWriteTexture",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 6,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "queue",
			},
			{
				.type = KOS_TYPE_BUF,
				.name = "destination",
			},
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "data",
			},
			{
				.type = KOS_TYPE_U32,
				.name = "dataSize",
			},
			{
				.type = KOS_TYPE_BUF,
				.name = "dataLayout",
			},
			{
				.type = KOS_TYPE_BUF,
				.name = "writeSize",
			},
		},
	},
	{
		.name = "wgpuQueueAddRef",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "queue",
			},
		},
	},
	{
		.name = "wgpuQueueRelease",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "queue",
			},
		},
	},
	{
		.name = "wgpuRenderBundleSetLabel",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "renderBundle",
			},
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "label",
			},
		},
	},
	{
		.name = "wgpuRenderBundleAddRef",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "renderBundle",
			},
		},
	},
	{
		.name = "wgpuRenderBundleRelease",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "renderBundle",
			},
		},
	},
	{
		.name = "wgpuRenderBundleEncoderDraw",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 5,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "renderBundleEncoder",
			},
			{
				.type = KOS_TYPE_U32,
				.name = "vertexCount",
			},
			{
				.type = KOS_TYPE_U32,
				.name = "instanceCount",
			},
			{
				.type = KOS_TYPE_U32,
				.name = "firstVertex",
			},
			{
				.type = KOS_TYPE_U32,
				.name = "firstInstance",
			},
		},
	},
	{
		.name = "wgpuRenderBundleEncoderDrawIndexed",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 6,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "renderBundleEncoder",
			},
			{
				.type = KOS_TYPE_U32,
				.name = "indexCount",
			},
			{
				.type = KOS_TYPE_U32,
				.name = "instanceCount",
			},
			{
				.type = KOS_TYPE_U32,
				.name = "firstIndex",
			},
			{
				.type = KOS_TYPE_I32,
				.name = "baseVertex",
			},
			{
				.type = KOS_TYPE_U32,
				.name = "firstInstance",
			},
		},
	},
	{
		.name = "wgpuRenderBundleEncoderDrawIndexedIndirect",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 3,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "renderBundleEncoder",
			},
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "indirectBuffer",
			},
			{
				.type = KOS_TYPE_U64,
				.name = "indirectOffset",
			},
		},
	},
	{
		.name = "wgpuRenderBundleEncoderDrawIndirect",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 3,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "renderBundleEncoder",
			},
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "indirectBuffer",
			},
			{
				.type = KOS_TYPE_U64,
				.name = "indirectOffset",
			},
		},
	},
	{
		.name = "wgpuRenderBundleEncoderFinish",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "renderBundleEncoder",
			},
			{
				.type = KOS_TYPE_BUF,
				.name = "descriptor",
			},
		},
	},
	{
		.name = "wgpuRenderBundleEncoderInsertDebugMarker",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "renderBundleEncoder",
			},
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "markerLabel",
			},
		},
	},
	{
		.name = "wgpuRenderBundleEncoderPopDebugGroup",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "renderBundleEncoder",
			},
		},
	},
	{
		.name = "wgpuRenderBundleEncoderPushDebugGroup",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "renderBundleEncoder",
			},
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "groupLabel",
			},
		},
	},
	{
		.name = "wgpuRenderBundleEncoderSetBindGroup",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 5,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "renderBundleEncoder",
			},
			{
				.type = KOS_TYPE_U32,
				.name = "groupIndex",
			},
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "group",
			},
			{
				.type = KOS_TYPE_U32,
				.name = "dynamicOffsetCount",
			},
			{
				.type = KOS_TYPE_BUF,
				.name = "dynamicOffsets",
			},
		},
	},
	{
		.name = "wgpuRenderBundleEncoderSetIndexBuffer",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 5,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "renderBundleEncoder",
			},
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "buffer",
			},
			{
				.type = KOS_TYPE_U32,
				.name = "format",
			},
			{
				.type = KOS_TYPE_U64,
				.name = "offset",
			},
			{
				.type = KOS_TYPE_U64,
				.name = "size",
			},
		},
	},
	{
		.name = "wgpuRenderBundleEncoderSetLabel",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "renderBundleEncoder",
			},
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "label",
			},
		},
	},
	{
		.name = "wgpuRenderBundleEncoderSetPipeline",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "renderBundleEncoder",
			},
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "pipeline",
			},
		},
	},
	{
		.name = "wgpuRenderBundleEncoderSetVertexBuffer",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 5,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "renderBundleEncoder",
			},
			{
				.type = KOS_TYPE_U32,
				.name = "slot",
			},
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "buffer",
			},
			{
				.type = KOS_TYPE_U64,
				.name = "offset",
			},
			{
				.type = KOS_TYPE_U64,
				.name = "size",
			},
		},
	},
	{
		.name = "wgpuRenderBundleEncoderAddRef",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "renderBundleEncoder",
			},
		},
	},
	{
		.name = "wgpuRenderBundleEncoderRelease",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "renderBundleEncoder",
			},
		},
	},
	{
		.name = "wgpuRenderPassEncoderBeginOcclusionQuery",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "renderPassEncoder",
			},
			{
				.type = KOS_TYPE_U32,
				.name = "queryIndex",
			},
		},
	},
	{
		.name = "wgpuRenderPassEncoderDraw",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 5,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "renderPassEncoder",
			},
			{
				.type = KOS_TYPE_U32,
				.name = "vertexCount",
			},
			{
				.type = KOS_TYPE_U32,
				.name = "instanceCount",
			},
			{
				.type = KOS_TYPE_U32,
				.name = "firstVertex",
			},
			{
				.type = KOS_TYPE_U32,
				.name = "firstInstance",
			},
		},
	},
	{
		.name = "wgpuRenderPassEncoderDrawIndexed",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 6,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "renderPassEncoder",
			},
			{
				.type = KOS_TYPE_U32,
				.name = "indexCount",
			},
			{
				.type = KOS_TYPE_U32,
				.name = "instanceCount",
			},
			{
				.type = KOS_TYPE_U32,
				.name = "firstIndex",
			},
			{
				.type = KOS_TYPE_I32,
				.name = "baseVertex",
			},
			{
				.type = KOS_TYPE_U32,
				.name = "firstInstance",
			},
		},
	},
	{
		.name = "wgpuRenderPassEncoderDrawIndexedIndirect",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 3,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "renderPassEncoder",
			},
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "indirectBuffer",
			},
			{
				.type = KOS_TYPE_U64,
				.name = "indirectOffset",
			},
		},
	},
	{
		.name = "wgpuRenderPassEncoderDrawIndirect",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 3,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "renderPassEncoder",
			},
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "indirectBuffer",
			},
			{
				.type = KOS_TYPE_U64,
				.name = "indirectOffset",
			},
		},
	},
	{
		.name = "wgpuRenderPassEncoderEnd",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "renderPassEncoder",
			},
		},
	},
	{
		.name = "wgpuRenderPassEncoderEndOcclusionQuery",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "renderPassEncoder",
			},
		},
	},
	{
		.name = "wgpuRenderPassEncoderExecuteBundles",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 3,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "renderPassEncoder",
			},
			{
				.type = KOS_TYPE_U32,
				.name = "bundleCount",
			},
			{
				.type = KOS_TYPE_BUF,
				.name = "bundles",
			},
		},
	},
	{
		.name = "wgpuRenderPassEncoderInsertDebugMarker",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "renderPassEncoder",
			},
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "markerLabel",
			},
		},
	},
	{
		.name = "wgpuRenderPassEncoderPopDebugGroup",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "renderPassEncoder",
			},
		},
	},
	{
		.name = "wgpuRenderPassEncoderPushDebugGroup",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "renderPassEncoder",
			},
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "groupLabel",
			},
		},
	},
	{
		.name = "wgpuRenderPassEncoderSetBindGroup",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 5,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "renderPassEncoder",
			},
			{
				.type = KOS_TYPE_U32,
				.name = "groupIndex",
			},
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "group",
			},
			{
				.type = KOS_TYPE_U32,
				.name = "dynamicOffsetCount",
			},
			{
				.type = KOS_TYPE_BUF,
				.name = "dynamicOffsets",
			},
		},
	},
	{
		.name = "wgpuRenderPassEncoderSetBlendConstant",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "renderPassEncoder",
			},
			{
				.type = KOS_TYPE_BUF,
				.name = "color",
			},
		},
	},
	{
		.name = "wgpuRenderPassEncoderSetIndexBuffer",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 5,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "renderPassEncoder",
			},
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "buffer",
			},
			{
				.type = KOS_TYPE_U32,
				.name = "format",
			},
			{
				.type = KOS_TYPE_U64,
				.name = "offset",
			},
			{
				.type = KOS_TYPE_U64,
				.name = "size",
			},
		},
	},
	{
		.name = "wgpuRenderPassEncoderSetLabel",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "renderPassEncoder",
			},
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "label",
			},
		},
	},
	{
		.name = "wgpuRenderPassEncoderSetPipeline",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "renderPassEncoder",
			},
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "pipeline",
			},
		},
	},
	{
		.name = "wgpuRenderPassEncoderSetScissorRect",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 5,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "renderPassEncoder",
			},
			{
				.type = KOS_TYPE_U32,
				.name = "x",
			},
			{
				.type = KOS_TYPE_U32,
				.name = "y",
			},
			{
				.type = KOS_TYPE_U32,
				.name = "width",
			},
			{
				.type = KOS_TYPE_U32,
				.name = "height",
			},
		},
	},
	{
		.name = "wgpuRenderPassEncoderSetStencilReference",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "renderPassEncoder",
			},
			{
				.type = KOS_TYPE_U32,
				.name = "reference",
			},
		},
	},
	{
		.name = "wgpuRenderPassEncoderSetVertexBuffer",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 5,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "renderPassEncoder",
			},
			{
				.type = KOS_TYPE_U32,
				.name = "slot",
			},
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "buffer",
			},
			{
				.type = KOS_TYPE_U64,
				.name = "offset",
			},
			{
				.type = KOS_TYPE_U64,
				.name = "size",
			},
		},
	},
	{
		.name = "wgpuRenderPassEncoderSetViewport",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 7,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "renderPassEncoder",
			},
			{
				.type = KOS_TYPE_F32,
				.name = "x",
			},
			{
				.type = KOS_TYPE_F32,
				.name = "y",
			},
			{
				.type = KOS_TYPE_F32,
				.name = "width",
			},
			{
				.type = KOS_TYPE_F32,
				.name = "height",
			},
			{
				.type = KOS_TYPE_F32,
				.name = "minDepth",
			},
			{
				.type = KOS_TYPE_F32,
				.name = "maxDepth",
			},
		},
	},
	{
		.name = "wgpuRenderPassEncoderAddRef",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "renderPassEncoder",
			},
		},
	},
	{
		.name = "wgpuRenderPassEncoderRelease",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "renderPassEncoder",
			},
		},
	},
	{
		.name = "wgpuRenderPipelineGetBindGroupLayout",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "renderPipeline",
			},
			{
				.type = KOS_TYPE_U32,
				.name = "groupIndex",
			},
		},
	},
	{
		.name = "wgpuRenderPipelineSetLabel",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "renderPipeline",
			},
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "label",
			},
		},
	},
	{
		.name = "wgpuRenderPipelineAddRef",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "renderPipeline",
			},
		},
	},
	{
		.name = "wgpuRenderPipelineRelease",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "renderPipeline",
			},
		},
	},
	{
		.name = "wgpuSamplerSetLabel",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "sampler",
			},
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "label",
			},
		},
	},
	{
		.name = "wgpuSamplerAddRef",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "sampler",
			},
		},
	},
	{
		.name = "wgpuSamplerRelease",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "sampler",
			},
		},
	},
	{
		.name = "wgpuShaderModuleGetCompilationInfo",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "shaderModule",
			},
			{
				.type = KOS_TYPE_BUF,
				.name = "callbackInfo",
			},
		},
	},
	{
		.name = "wgpuShaderModuleSetLabel",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "shaderModule",
			},
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "label",
			},
		},
	},
	{
		.name = "wgpuShaderModuleAddRef",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "shaderModule",
			},
		},
	},
	{
		.name = "wgpuShaderModuleRelease",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "shaderModule",
			},
		},
	},
	{
		.name = "wgpuSupportedFeaturesFreeMembers",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_BUF,
				.name = "supportedFeatures",
			},
		},
	},
	{
		.name = "wgpuSupportedWGSLLanguageFeaturesFreeMembers",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_BUF,
				.name = "supportedWGSLLanguageFeatures",
			},
		},
	},
	{
		.name = "wgpuSurfaceConfigure",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "surface",
			},
			{
				.type = KOS_TYPE_BUF,
				.name = "config",
			},
		},
	},
	{
		.name = "wgpuSurfaceGetCapabilities",
		.ret_type = KOS_TYPE_U32,
		.param_count = 3,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "surface",
			},
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "adapter",
			},
			{
				.type = KOS_TYPE_BUF,
				.name = "capabilities",
			},
		},
	},
	{
		.name = "wgpuSurfaceGetCurrentTexture",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "surface",
			},
			{
				.type = KOS_TYPE_BUF,
				.name = "surfaceTexture",
			},
		},
	},
	{
		.name = "wgpuSurfacePresent",
		.ret_type = KOS_TYPE_U32,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "surface",
			},
		},
	},
	{
		.name = "wgpuSurfaceUnconfigure",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "surface",
			},
		},
	},
	{
		.name = "wgpuSurfaceAddRef",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "surface",
			},
		},
	},
	{
		.name = "wgpuSurfaceRelease",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "surface",
			},
		},
	},
	{
		.name = "wgpuSurfaceCapabilitiesFreeMembers",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "surfaceCapabilities",
			},
		},
	},
	{
		.name = "wgpuTextureCreateView",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "texture",
			},
			{
				.type = KOS_TYPE_BUF,
				.name = "descriptor",
			},
		},
	},
	{
		.name = "wgpuTextureDestroy",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "texture",
			},
		},
	},
	{
		.name = "wgpuTextureGetDepthOrArrayLayers",
		.ret_type = KOS_TYPE_U32,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "texture",
			},
		},
	},
	{
		.name = "wgpuTextureGetDimension",
		.ret_type = KOS_TYPE_U32,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "texture",
			},
		},
	},
	{
		.name = "wgpuTextureGetFormat",
		.ret_type = KOS_TYPE_U32,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "texture",
			},
		},
	},
	{
		.name = "wgpuTextureGetHeight",
		.ret_type = KOS_TYPE_U32,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "texture",
			},
		},
	},
	{
		.name = "wgpuTextureGetMipLevelCount",
		.ret_type = KOS_TYPE_U32,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "texture",
			},
		},
	},
	{
		.name = "wgpuTextureGetSampleCount",
		.ret_type = KOS_TYPE_U32,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "texture",
			},
		},
	},
	{
		.name = "wgpuTextureGetUsage",
		.ret_type = KOS_TYPE_OPAQUE_PTR,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "texture",
			},
		},
	},
	{
		.name = "wgpuTextureGetWidth",
		.ret_type = KOS_TYPE_U32,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "texture",
			},
		},
	},
	{
		.name = "wgpuTextureSetLabel",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "texture",
			},
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "label",
			},
		},
	},
	{
		.name = "wgpuTextureAddRef",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "texture",
			},
		},
	},
	{
		.name = "wgpuTextureRelease",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "texture",
			},
		},
	},
	{
		.name = "wgpuTextureViewSetLabel",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 2,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "textureView",
			},
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "label",
			},
		},
	},
	{
		.name = "wgpuTextureViewAddRef",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "textureView",
			},
		},
	},
	{
		.name = "wgpuTextureViewRelease",
		.ret_type = KOS_TYPE_VOID,
		.param_count = 1,
		.params = (kos_param_t[]) {
			{
				.type = KOS_TYPE_OPAQUE_PTR,
				.name = "textureView",
			},
		},
	},
// FNS:END
	// clang-format on
};
